services:
  trino:
    networks:
      - trino-net
    ports:
      - "8080:8080"
    image: "trinodb/trino:471"
    environment:
      CATALOG_MANAGEMENT: dynamic
      TRINO_HISTORY_FILE: /etc/trino/history-server/history.text
    volumes:
      - ./etc:/etc/trino

  postgres:
    networks:
      - trino-net
    ports:
      - "5432:5432"
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: trino-compose
      POSTGRES_PASSWORD: trino-compose
      POSTGRES_DB: metastore

  hive-metastore:
    networks:
      - trino-net
    hostname: hive-metastore
    image: 'starburstdata/hive:3.1.2-e.18'
    ports:
      - '9083:9083' 
    environment:
       HIVE_METASTORE_DRIVER: org.postgresql.Driver
       HIVE_METASTORE_JDBC_URL: jdbc:postgresql://metastore_db:5432/metastore
       HIVE_METASTORE_USER: trino-compose
       HIVE_METASTORE_PASSWORD: trino-compose
       HIVE_METASTORE_WAREHOUSE_DIR: s3://datalake/
       S3_ENDPOINT: http://minio:9000
       S3_ACCESS_KEY: minio
       S3_SECRET_KEY: minio123
       S3_PATH_STYLE_ACCESS: "true"
       REGION: "us-east-1"
       GOOGLE_CLOUD_KEY_FILE_PATH: ""
       AZURE_ADL_CLIENT_ID: ""
       AZURE_ADL_CREDENTIAL: ""
       AZURE_ADL_REFRESH_URL: ""
       AZURE_ABFS_STORAGE_ACCOUNT: ""
       AZURE_ABFS_ACCESS_KEY: ""
       AZURE_WASB_STORAGE_ACCOUNT: ""
       AZURE_ABFS_OAUTH: ""
       AZURE_ABFS_OAUTH_TOKEN_PROVIDER: ""
       AZURE_ABFS_OAUTH_CLIENT_ID: ""
       AZURE_ABFS_OAUTH_SECRET: ""
       AZURE_ABFS_OAUTH_ENDPOINT: ""
       AZURE_WASB_ACCESS_KEY: ""
    depends_on:
      - postgres
  minio:
    networks:
      - trino-net
    hostname: minio
    image: 'minio/minio'
    container_name: minio
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
      AWS_REGION: us-east-1
    command: server /data --console-address ":9001"

  mc-job:
    networks:
      - trino-net
    image: 'minio/minio'
    entrypoint: |
      /bin/bash -c "
      sleep 5;
      /usr/bin/mc config --quiet host add myminio http://minio:9000 minio minio123;
      /usr/bin/mc mb --quiet myminio/datalake
      "
    depends_on:
      - minio

networks:
  trino-net:
    driver: bridge
